# Site
name: "EconThaki"
title: "EconThaki"
description: "EconThaki por una academia diversa"
meta_description: "EconThaki por una academia diversa"
logo: 'assets/images/'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/'

email: 'econ.mentoringp@gmail.com'
google_analytics: 'G-2BG8KTZQ3G'

disqus: 'demowebsite'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  econthaki:
    name: EconThaki
    display_name: EconThaki
    email: econ.mentoringp@gmail.com
    web: https://econthaki.github.io
    twitter: https://twitter.com/EconThaki
    description: "EconThaki por una academia diversa"
  selene:
    name: Selene
    display_name: Selene
    email: scueva@povertyactionlab.org
    twitter: https://twitter.com/selenedelpi
    description: "Selene es Investigadora Asociada en JPAL"
  brian:
    name: Brian
    display_name: Brian
    email: dazavbn@gmail.com
    twitter: https://twitter.com/bdazav
    description: "Brian es Poeta, catador de caldo de pollo y PhD student en UMICH"
  paola:
    name: Paola
    display_name: Paola
    email: paola.villapar@gmail.com
    twitter: https://twitter.com/paola_villaparo
    description: "Paola es Pre-doctoral fellow en Princeton"
  gabriela: 
    name: Gabriela
    display_name: Gabriela
    email:  gaby.lecaro@gmail.com
    twitter: https://twitter.com/GabLecaro
    description: "Investigadora Asociada en IPA"
  marcy: 
    name: Marcy
    display_name: Marcy
    email: mgcastro@pucp.pe
    twitter: https://twitter.com/mgcastrolivano
    description: "Marcy es asistente de investigaci√≥n en el BID"    
  jostin:  
    name: Jostin
    display_name: Jostin
    email: jostin.kitmang@gmail.com
    twitter: https://twitter.com/JKitmang
    description: "Jostin es Investigador Asociado en JPAL"    


# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge